import type { Metadata } from "next";
import {
  Inter,
  Space_Grotesk,
  Hanken_Grotesk,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "../components/provider";
import { StarknetProvider } from "@/components/starknetProvider";
import Wallet from "@/components/Modal/Wallet/Wallet";
import StarknetWallet from "@/components/Modal/Wallet/StarknetWallet";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  display: "swap",
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});
export const metadata: Metadata = {
  title: "UNIX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${space.variable} ${hanken.variable} ${playfair.variable}`}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="font-hanken text-white bg-black-1">
        <StarknetProvider>
          <Provider>
            <Navbar />
            <div className="bg-black-1 flex justify-end gap-5 items-center mr-5 mt-8">
              <Wallet>Connect Base</Wallet>
              <StarknetWallet />
            </div>
            <div className="px-4 py-32 sm:ml-64 bg-black-1 text-white">{children}</div>
          </Provider>
        </StarknetProvider>
        <Toaster />
      </body>
    </html>
  );
}
