import type { Metadata } from "next";
import { Inter,  Space_Grotesk,
  Hanken_Grotesk,
  Playfair_Display, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  display: "swap",
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});
export const metadata: Metadata = {
  title: "UNIX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en" className={`${space.variable} ${hanken.variable} ${playfair.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="font-hanken text-white">
        <div>
          <Navbar/>
          <div className="flex justify-end gap-8 my-3 mr-6">
          <Link href="/">
          <button className="bg-[#0039a6] px-8 py-2 rounded-md"> Connect MetaMask</button>
          </Link>
          <Link href="/">
            <button className="bg-[#0039a6] px-8 py-2 rounded-md"> Connect Argent</button>
          </Link>
          </div>
        </div>
        <div className="p-4 sm:ml-64 min-h-screen bg-black-1 text-white">
          {children}
        </div>
        </body>
    </html>
  );
}
